// Netlify Edge Function: serves /sitemap.xml as real application/xml.
// Proxies the Supabase pd-sitemap function, injects static pages, fixes Content-Type.
export default async () => {
  const res = await fetch(
    "https://kohpsobftjrxdjtnclpx.supabase.co/functions/v1/pd-sitemap"
  );
  let body = await res.text();
  const extra =
    "<url><loc>https://powerdiesel.pro/roadside</loc><changefreq>weekly</changefreq><priority>0.9</priority></url>" +
    "<url><loc>https://powerdiesel.pro/mechanic</loc><changefreq>weekly</changefreq><priority>0.9</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-hialeah</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-doral</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-fort-lauderdale</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-homestead</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-i95-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-i75-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-florida-turnpike-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-medley</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-miami-gardens</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-pembroke-pines</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-port-of-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-port-everglades</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/heavy-duty-towing-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/semi-truck-tire-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-broke-down-miami-what-to-do</loc><changefreq>monthly</changefreq><priority>0.6</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-hollywood</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-miramar</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-pompano-beach</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-coral-springs</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-sunrise</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-plantation</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-davie</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-kendall</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-opa-locka</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-hialeah-gardens</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-north-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-dania-beach</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-deerfield-beach</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-cutler-bay</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-miami-lakes</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-florida-city</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-miami-springs</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-westchester</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-the-hammocks</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-key-largo</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-islamorada</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-marathon</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-mechanic-key-west</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-palmetto-expressway-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-dolphin-expressway-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-i595-fort-lauderdale</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-us1-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-us27-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-repair-miami-airport-mia</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/dpf-cleaning-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-ac-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/dot-inspection-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/mobile-truck-welding-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-brake-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-electrical-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/turbocharger-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-injector-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/reefer-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-jump-start-fuel-delivery-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/mobile-diesel-repair-cost-miami</loc><changefreq>monthly</changefreq><priority>0.6</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-derate-dpf-regen-explained</loc><changefreq>monthly</changefreq><priority>0.6</priority></url>" +
    "<url><loc>https://powerdiesel.pro/dot-inspection-checklist-truckers</loc><changefreq>monthly</changefreq><priority>0.6</priority></url>" +
    "<url><loc>https://powerdiesel.pro/service-areas</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/limpieza-reparacion-dpf-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/inspeccion-dot-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-aire-acondicionado-camion-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-frenos-camion-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-electrica-camion-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/grua-remolque-pesado-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/arranque-y-combustible-camion-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-engine-repair-rebuild-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-diagnostics-scanning-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-tuning-ecm-programming-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/cummins-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/detroit-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/paccar-mx13-engine-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/international-maxxforce-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/duramax-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/powerstroke-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/volvo-mack-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/cat-diesel-engine-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-cummins-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-detroit-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-paccar-mx13-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-international-maxxforce-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-duramax-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-powerstroke-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-volvo-mack-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-cat-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-transmission-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-clutch-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-radiator-cooling-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-suspension-airbag-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-preventive-maintenance-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/fleet-diesel-repair-maintenance-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/semi-trailer-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/box-truck-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/dump-truck-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-bus-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/services</loc><changefreq>weekly</changefreq><priority>0.9</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/servicios</loc><changefreq>weekly</changefreq><priority>0.9</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-hialeah</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-doral</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-medley</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-homestead</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-kendall</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-miami-gardens</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-hollywood</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-miramar</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mecanico-diesel-pembroke-pines</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/def-scr-egr-system-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-sistema-def-scr-egr-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/freightliner-truck-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-freightliner-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/isuzu-hino-box-truck-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-isuzu-hino-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/kenworth-peterbilt-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-kenworth-peterbilt-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-pickup-truck-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-pickup-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/sprinter-van-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-sprinter-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/truck-check-engine-light-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/luz-check-engine-camion-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/heavy-equipment-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-maquinaria-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-transmision-camion-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-embrague-camion-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/engine-mount-replacement-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reemplazo-soportes-motor-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/diesel-cylinder-head-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-cabeza-cilindros-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-inyectores-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-turbo-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mantenimiento-preventivo-camiones-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-flotas-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/asistencia-carretera-camiones-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-trailer-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-llantas-camion-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/diagnostico-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/programacion-ecm-tuning-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/reparacion-reefer-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-cummins-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-cummins-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-detroit-diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-detroit-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-dd15-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-dd15-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-volvo-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-volvo-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-mack-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-mack-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-freightliner-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-freightliner-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-paccar-mx13-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-paccar-mx13-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-diesel-repair-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejores-reparaciones-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-duramax-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-duramax-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-power-stroke-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-power-stroke-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-dt466-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-dt466-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-cummins-67-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-cummins-67-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-cummins-isx-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-cummins-isx-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-cummins-x15-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-cummins-x15-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-volvo-d13-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-volvo-d13-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-volvo-d12-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-volvo-d12-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-volvo-d16-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-volvo-d16-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-ram-diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-ram-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-ford-diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-ford-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-chevrolet-diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-chevrolet-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-titan-xd-diesel-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-titan-xd-diesel-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-freightliner-m2-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-freightliner-m2-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-caterpillar-equipment-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-equipo-caterpillar-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-john-deere-equipment-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-equipo-john-deere-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-bobcat-equipment-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-equipo-bobcat-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/best-kubota-equipment-mechanic-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" +
    "<url><loc>https://powerdiesel.pro/es/mejor-mecanico-equipo-kubota-miami</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>";
  if (body.includes("</urlset>")) {
    body = body.replace("</urlset>", extra + "</urlset>");
  }
  return new Response(body, {
    status: res.status,
    headers: {
      "content-type": "application/xml; charset=utf-8",
      "cache-control": "public, max-age=600",
    },
  });
};

export const config = { path: "/sitemap.xml" };
